version: '3'
services:
  app1:
    restart: always
    image: captainkay101/cloudapp1:app1
    expose:
      - "5000"
    environment:
      APP_NAME: "application 1"
  app2:
    restart: always
    image: captainkay101/cloudapp2:app1
    expose:
      - "5000"
    environment:
      APP_NAME: "application 2"
  app3:
    restart: always
    image: captainkay101/cloudapp3:app1
    expose:
      - "5000"
    environment:
      APP_NAME: "application 3"
  nginx:
    restart: always
    image: captainkay101/cloudnginx:nginx
    ports:
      - 8000:80
    links:
      - app1:app1
      - app2:app2
      - app3:app3